name: DevOps CI/CD Pipeline - Firebase

on:
  push:
    branches:
      - main  # Change to your production branch

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - run: npm ci

      # Lint and code quality check
      - run: |
          npm run lint
          npx prettier --check .

      # Run unit tests
      - run: npm test

      # Optional security scan
      - run: npm audit --audit-level=high || echo "No critical vulnerabilities"

      # Build project
      - run: npm run build

      # Deploy to Firebase Hosting
      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
